### ISSUE TITLE
你好，请问“data_bin_new”下的文件格式是什么样子的？

### ISSUE THREAD

**Issue by Ant0082** [OpenBMB/CPM-Live#142]
你好，请问“data_bin_new”下的文件格式是什么样子的？能给个示例吗？
学习下CPM_Live的代码。

**Comment by zh-zheng** [comment]
Hi,
数据的生成代码在[这里](https://github.com/OpenBMB/CPM-Live/blob/master/cpm-live/tools/preprocess_cpm_live.py#L40)

**Comment by Ant0082** [comment]
> Hi, 数据的生成代码在[这里](https://github.com/OpenBMB/CPM-Live/blob/master/cpm-live/tools/preprocess_cpm_live.py#L40)

好的，多谢解释。
