### ISSUE TITLE
请问基于CPM-Ant的智取标题模型有开源计划吗

### ISSUE THREAD

**Issue by MingFL** [OpenBMB/CPM-Live#180]
经过在线测试，感觉效果不错。但没有对应的语料很难finetune出类似效果的模型。
所以请问智取标题这个模型有开源么

**Comment by zh-zheng** [comment]
你好，我们会在CPM-Live二期模型（CPM-Bee）中将标题生成作为一项基础能力，模型也会开源发布，欢迎继续关注！

**Comment by MingFL** [comment]
> 你好，我们会在CPM-Live二期模型（CPM-Bee）中将标题生成作为一项基础能力，模型也会开源发布，欢迎继续关注！

非常感谢回复，方便问一下CPM-Bee发布的大概时间吗

**Comment by zh-zheng** [comment]
> 非常感谢回复，方便问一下CPM-Bee发布的大概时间吗

预计会在年底
