### ISSUE TITLE
请问你说中国人吗？

### ISSUE THREAD

**Issue by RomanceLink** [OpenBMB/CPM-Live#184]
如果不是就当我没问，如果是请你写上中文readme再来推广！！！

**Comment by Potion1337** [comment]
脑残

**Comment by taki-na** [comment]
差不多得了😅

**Comment by jayzzhou-thu** [comment]
感谢题主的建议，我们将尽快翻译文档的中文版并上线。
另外希望大家能够文明发言，共同建立文明健康的社区风气。
如有违反，我们将组织继续访问本项目。
