### ISSUE TITLE
What is the difference between CPM-Ant+ and CPM-Ant?

### ISSUE THREAD

**Issue by Ant0082** [OpenBMB/CPM-Live#207]

**Comment by Ant0082** [comment]
Is it fine-tuned on task-specific datasets using OpenDelta ？

**Comment by zh-zheng** [comment]
> Is it fine-tuned on task-specific datasets using OpenDelta ？

No. We added data corresponding to these tasks in the pre-training stage.

**Comment by zh-zheng** [comment]
Close this due to inactivity. If you have any other questions, you can re-open this issue.
