### ISSUE TITLE
项目文档说明，还有模型使用说明太少了，例子也没有，太难了

### ISSUE THREAD

**Issue by touwenameng** [OpenBMB/CPM-Live#230]

**Comment by zh-zheng** [comment]
Hi,
感谢关注。模型使用说明在各自模型的README里（[CPM-Ant](https://github.com/OpenBMB/CPM-Live/tree/cpm-ant/cpm-live), [CPM-Ant+](https://github.com/OpenBMB/CPM-Live/tree/cpm-ant-plus/cpm-live)）。下游任务上微调模型的例子可以参考[examples](https://github.com/OpenBMB/CPM-Live/tree/cpm-ant-plus/cpm-live/examples)文件夹。
如果您有什么问题或建议，欢迎反馈，我们会对文档进行完善。

**Comment by touwenameng** [comment]
文本可控生成的prompt怎么设置，是pretrain还是finetune，具体格式是咋样的，翻遍工程没找到

**Comment by zh-zheng** [comment]
能否简单描述下具体的需求呢？是想微调模型用于可控生成吗？

**Comment by touwenameng** [comment]
是的，就是根据知识图谱的关键词输入，prompt微调大模型进行可控文本生成

**Comment by zh-zheng** [comment]
> 是的，就是根据知识图谱的关键词输入，prompt微调大模型进行可控文本生成

目前比较推荐使用delta tuning微调CPM-Ant系列模型，你这个任务可以直接当做文本生成任务来训练（参考examples中的LCSTS）。你只需要将训练数据格式化一下，将`feature`作为输入，`desc`作为target。举个例子，你的输入格式可以为：

`{"input": "品牌：小米；公司：小米；产品：小米12S Pro[文章]", "target": "小米公司昨天发布了小米12S Pro。"}`

**Comment by touwenameng** [comment]
多谢，我看看哈

**Comment by touwenameng** [comment]
训练50轮之后得到了十几M的best.pt，但是infer推理的结果好像不对，只显示了英文，还有很多-----------
[" on the internet. The company's website is at www.TCL.com. ----------------------------------", ", easy to use, and the price is right.\"", " "                                                   ", " ----------------------------------------------------", "                                                   ", " The company's website is at www.ambridge.com.au. The company's website is at www.ambridge.com.au. The company's website is at www.ambridge.com.au.", " [price] [price] [price] [price] [price] [price] [price] [price] [price] [price] [price] [price] [price] [price] [price] [price] [price]",

**Comment by touwenameng** [comment]
infer的中文推理结果没出来，input的参数和训练集高度一样
