### ISSUE TITLE
![image](https://user-images.githubusercontent.com/92961574/205198889-81b48fa4-e5dd-4aa7-8a77-2251e9881c91.png)

### ISSUE THREAD

**Issue by touwenameng** [OpenBMB/CPM-Live#258]
![image](https://user-images.githubusercontent.com/92961574/205198889-81b48fa4-e5dd-4aa7-8a77-2251e9881c91.png)
代码配置如上所示，train.json9万条数据，eval9000条数据

_Originally posted by @touwenameng in https://github.com/OpenBMB/CPM-Live/issues/254#issuecomment-1334675958_

**Comment by zh-zheng** [comment]
请不要再另开issue，谢谢
