### ISSUE TITLE
CPM-Ant zero-shot支持Promt做文本续写吗？

### ISSUE THREAD

**Issue by greenteaofwhu** [OpenBMB/CPM-Live#338]

**Comment by greenteaofwhu** [comment]
当前只在官网的样例里看到生成标题，不知道是否必须要Finetune以后才能做类似CPM-Bee那种文本续写功能？

**Comment by zh-zheng** [comment]
CPM-Ant可以做文本续写，可以使用[`text_generation.py`](https://github.com/OpenBMB/CPM-Live/blob/cpm-ant/cpm-live/text_generation.py)测试下。

**Comment by greenteaofwhu** [comment]
明白了，感谢回答，另外请问下huggingface上的模型（https://huggingface.co/openbmb/cpm-ant-10b/tree/main）和主页下载链接https://openbmb.oss-cn-hongkong.aliyuncs.com/model_center/cpmlive-10b/cpm_live_10B.zip这个模型是同一个吗？因为主页下载链接的这个zip太大了，总是下载到最后报错了，想尝试用huggingface上面的模型来测试。

**Comment by greenteaofwhu** [comment]
> 明白了，感谢回答，另外请问下huggingface上的模型（[https://huggingface.co/openbmb/cpm-ant-10b/tree/main）和主页下载链接https://openbmb.oss-cn-hongkong.aliyuncs.com/model_center/cpmlive-10b/cpm_live_10B.zip这个模型是同一个吗？因为主页下载链接的这个zip太大了，总是下载到最后报错了，想尝试用huggingface上面的模型来测试。](https://huggingface.co/openbmb/cpm-ant-10b/tree/main%EF%BC%89%E5%92%8C%E4%B8%BB%E9%A1%B5%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5https://openbmb.oss-cn-hongkong.aliyuncs.com/model_center/cpmlive-10b/cpm_live_10B.zip%E8%BF%99%E4%B8%AA%E6%A8%A1%E5%9E%8B%E6%98%AF%E5%90%8C%E4%B8%80%E4%B8%AA%E5%90%97%EF%BC%9F%E5%9B%A0%E4%B8%BA%E4%B8%BB%E9%A1%B5%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5%E7%9A%84%E8%BF%99%E4%B8%AAzip%E5%A4%AA%E5%A4%A7%E4%BA%86%EF%BC%8C%E6%80%BB%E6%98%AF%E4%B8%8B%E8%BD%BD%E5%88%B0%E6%9C%80%E5%90%8E%E6%8A%A5%E9%94%99%E4%BA%86%EF%BC%8C%E6%83%B3%E5%B0%9D%E8%AF%95%E7%94%A8huggingface%E4%B8%8A%E9%9D%A2%E7%9A%84%E6%A8%A1%E5%9E%8B%E6%9D%A5%E6%B5%8B%E8%AF%95%E3%80%82)
下载10B模型后解压 报这个错误
![image](https://user-images.githubusercontent.com/29090584/217793668-b7293935-4d25-42b8-a90d-052f72038da3.png)
