### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by jiangix-paper** [OpenBMB/CPM-Live#345]
你好，如果不使用bminf，text_generation.py中默认的显存是12G，我现在显卡是16G的v100，在使用默认配置运行text_generation.py时显示cuda out of memory，请问是什么原因呢

**Comment by a710128** [comment]
不使用BMInf时，现存限制不会生效。

**Comment by jiangix-paper** [comment]
请问不使用BMInf的时候，text_generation.py运行大概要多少的显存，如果单卡16G会out of memory的话，能否支持多卡推理呢

**Comment by zh-zheng** [comment]
> 请问不使用BMInf的时候，text_generation.py运行大概要多少的显存，如果单卡16G会out of memory的话，能否支持多卡推理呢

当前的代码不支持多卡推理。
